
services:
  db:
    image: postgres
    container_name: productos-fabricantes_sql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_productos-fabricantes
    restart: always
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fluxit@flux.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data: